/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Reservation = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'date' : IDL.Text,
  'specialRequests' : IDL.Text,
  'time' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'phoneNumber' : IDL.Text,
  'numberOfGuests' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createReservation' : IDL.Func([Reservation], [IDL.Nat], []),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getReservationById' : IDL.Func([IDL.Nat], [Reservation], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Reservation = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'date' : IDL.Text,
    'specialRequests' : IDL.Text,
    'time' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'phoneNumber' : IDL.Text,
    'numberOfGuests' : IDL.Nat,
  });
  
  return IDL.Service({
    'createReservation' : IDL.Func([Reservation], [IDL.Nat], []),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getReservationById' : IDL.Func([IDL.Nat], [Reservation], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };